{% set version = "9.0.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://github.com/python-pillow/Pillow/archive/refs/tags/{{ version }}.tar.gz
  sha256: da6e69e9f11e9ea7081730abbf7bb8b0539cacfafa7a2ce934e1fe088db68fe7
  patches:
    - patches/0001-Build-without-USE_WIN32_FILEIO.patch
    - patches/0002-Do-not-quote-PILLOW_VERSION.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    # libraries, c.f. https://github.com/python-pillow/Pillow/blob/9.0.0/setup.py#L30-L38
    - freetype
    - jpeg
    - openjpeg
    - lcms2
    - libtiff
    - tk
    - zlib
  run:
    - python
    - freetype
    - jpeg
    - openjpeg
    - lcms2
    - libtiff
    - tk
    - zlib

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms
  source_files:
    - Tests/
  requires:
    - pytest
  commands:
    - pytest Tests -v

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  dev_url: https://github.com/python-pillow/Pillow/

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
    - h-vetinari
